---
title: "R Notebook"
output: html_notebook
---
1. Load adult.data into a dataframe in R. Note that adult.data does not have column names in
the first line so you need to set header=FALSE when you read the data then manually set the column
names. Inspect the dataset using “str” and “summary” functions. What is the type of each variable in
the dataset numeric/continuous or categorical/discrete? For each categorical variable explain whether
it is nominal or ordinal.

```{R}
  install.packages("stringr", "tidyverse")
  library(stringr)
  library(tidyverse)
  adult_data <- read.csv("adult.data", header = FALSE, na.strings = " ?")
  colnames(adult_data) <- c("age", "workclass", "fnlwgt", "education", "education-num", "marital-status", "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss", "hours-per-week", "native-country", "target")
  str(adult_data)
  summary(adult_data)
  # I had to do this for handling sparse data in native-country
  adult_data$`native-country` <- as.character(adult_data$`native-country`)
  adult_data$`native-country` <- str_trim(adult_data$`native-country`)
  adult_data$`native-country` <- as.factor(adult_data$`native-country`)
  adult_data$target <- as.character(adult_data$target)
  adult_data$target <- str_trim(adult_data$target)
  adult_data$target <- as.factor(adult_data$target)
  adult_data <- adult_data |>
    mutate(`native-country` = fct_na_value_to_level(`native-country`, level = "United-States")) |>
    mutate(`native-country` = fct_collapse(`native-country`,
      North_America = c("United-States", "Mexico", "Canada", "Cuba", "Puerto-Rico", "Trinadad&Tobago", "Honduras", "Guatemala", "El-Salvador", "Haiti", "Jamaica", "Dominican-Republic", "Nicaragua"),
      South_America = c("Columbia", "Ecuador", "Peru"),
      Europe = c("England", "France", "Germany", "Greece", "Holand-Netherlands", "Hungary", "Ireland", "Italy", "Poland", "Portugal", "Scotland", "Yugoslavia"),
      Asia = c("Cambodia", "China", "Hong", "India", "Iran", "Japan", "Laos", "Outlying-US(Guam-USVI-etc)", "Philippines", "Taiwan", "Thailand", "Vietnam"),
      Other = "South"
    ))
```

The type of each variable is as follows:

- age: continuous
- workclass: categorical/nominal
- fnlwgt: continuous
- education: categorical/ordinal
- education-num: continuous
- marital-status: categorical/nominal
- occupation: categorical/nominal
- relationship: categorical/nominal
- race: categorical/nominal
- sex: categorical/nominal
- capital-gain: continuous
- capital-loss: continuous
- hours-per-week: continuous
- native-country: categorical/nominal

2. There are some missing values in this dataset represented as “ ?” (Note: there is a space before
?) . Make sure that all “ ?” are converted to NAs. You can do so by setting “na.strings” parameters in
“read.csv” to “ ?”

- Done in the code block for question 1 above.

3. Set the random seed, and split the data to train/test. Use 80% of samples for training and the
remaining 20% for testing. You can use “sample” (similar to what we did in slide 37 of week 6 lecture
but you need to adjust1000 and 900 to the number of observations in your dataset and the size of the
sample) or alternatively, you can use “createDataPartition” method from caret package.

```{R}
  install.packages("caret")
  library(caret)
  set.seed(1234)
  train_index <- createDataPartition(adult_data$target, p = .8, list = FALSE, times = 1)
  adult_train <- adult_data[train_index,]
  adult_test <- adult_data[-train_index,]
```

4. Read the section on “Handling Missing Data” in chapter 13 of the textbook Machine
Learning with R. Find which columns/variables in the train and test set have missing values. Then
decide about how you want to impute the missing values in these columns. Explain why you chose
this imputation approach.
```{R}
  colSums(is.na(adult_data))
```

- There are three variables that have missing values, occupation and native-country. 
- After analyzing the variables I believe that imputing the native-country variable with just 'United-States' is the best thing to do here. I did this because of two main reasons, I don't think that the data is not missing at random(NMAR) and after analyzing the dataset the 'United-States' category makes up almost 90% of the choices for the entire data set while the native-country variable also has a relatively low amount of missing values. This means that if I set missing values to 'United-States' I am less likely to introduce bias.
- For the occupation variable this was harder. This one has a lot more missing values and I think that the missing values are not missing at random because I think people are less likely to report occupation if they are unemployed or have a low paying occupation.For this reason I chose to impute this data simply with the value 'Missing'.
- For workclass the situation is very similar to the occupation variable and for that reason I decided to take the same approach and set all of the NA/missing variables to 'Unknown'.

```{R}
  adult_train <- adult_train |>
    mutate(
      `native-country_mvi` = if_else(is.na(`native-country`), 1, 0),
      `native-country` = if_else(is.na(`native-country`), 'United-States', `native-country`),
      occupation_mvi = if_else(is.na(occupation), 1, 0),
      occupation = if_else(is.na(occupation), 'Unknown', occupation),
      workclass_mvi = if_else(is.na(workclass), 1, 0),
      workclass = if_else(is.na(workclass), 'Unknown', workclass)
    )

  adult_test <- adult_test |>
    mutate(
      `native-country_mvi` = if_else(is.na(`native-country`), 1, 0),
      `native-country` = if_else(is.na(`native-country`), 'United-States', `native-country`),
      occupation_mvi = if_else(is.na(occupation), 1, 0),
      occupation = if_else(is.na(occupation), 'Unknown', occupation),
      workclass_mvi = if_else(is.na(workclass), 1, 0),
      workclass = if_else(is.na(workclass), 'Unknown', workclass)
    )
```

5. Dealing with sparse data.I have decided to combine all values that are not 'United-States' into their respective continents, including the 'United-States' values. I will include Central American and Caribbean countries in North America. I have added this to the first code block. I did run into issues with untrimmed strings here in the data so I had to do trim strings for everything in native-country first for it to finally work. 

6. Use appropriate plots and statistic tests to find which variables in the dataset are associated with
“income”. Remove the variable(s) that are not associated with income.

- age: side by side boxplot and t-test - is associated
  - the side by side boxplot has some overlap but I think there is enough of a difference to believe that there is an association between age and target(>50k)
  - running the t-test produces a p-value of < .05 so we can reject the null hypothesis
```{R}
  plot(adult_data$age~as.factor(adult_data$target))
  t.test(adult_data$age~adult_data$target)
```

- workclass: mosaic plot and chi-square test - is associated
  - the mosaic plot shows that there are 4 values that were more likely to have > 50k income; federal, local-gov, self-employed-inc, and self-employed-no-inc. There was also one, private, that was less likely to have income > 50k. It also showed that Private had the most observations.
  - the chisq test showed that the p-value was < 2.2e-16 but gave a warning that the approximation may be incorrect so I also ran it with simulate.p.value = TRUE and the p-value was still 0.0004998 which is lower than 0.05 so we can reject the null hypothesis. This supports the mosaic plot and the variables are associated.
```{R}
  workclass_target_table <- table(adult_data$workclass, adult_data$target)
  mosaicplot(workclass_target_table, shade = TRUE)
  chisq.test(workclass_target_table)
  chisq.test(workclass_target_table, simulate.p.value = TRUE)
```

- fnlwgt: side by side box plots and t-test - not associated
  - the side by side box plots showed almost the exact same distributions which shows no association likely.
  - the t-test confirms this and returns a value of .08 which is > .05 so we should not reject the null hypothesis.
```{R}
  plot(adult_data$fnlwgt~as.factor(adult_data$target))
  t.test(adult_data$fnlwgt~adult_data$target)
```

- education: mosaic plot and chisq test - is associated
  - the mosaic plot shows that there are a lot of values that were less likely to make over 50K. There are also 4 values (Bachelors, Doctorate, Masters, and Prof-School) that are more likely to make over 50K
  - the chisq test evaluated a p-value that was smaller than 2.2e-16 without a warning so we can reject the null hypothesis
```{R}
  education_target_table <- table(adult_data$education, adult_data$target)
  mosaicplot(education_target_table, shade = TRUE)
  chisq.test(education_target_table)
```

- education-num: side by side box plots and t-test - associated
  - the side by side box plots shows little overlap and so the variables are likely associated
  - the t-test confirms this and returns a value < 2.2e-16 so we can reject the null hypothesis
```{R}
  plot(adult_data$`education-num`~as.factor(adult_data$target))
  t.test(adult_data$`education-num`~adult_data$target)
```

- marital-status: mosaic plot and chisq test - is associated
  - the mosaic plot shows that every value but Married-civ-spouse and Married-AF-spouse is more likely to earn less than 50K. Married-AF-spouse shows not much difference and Married-civ-spouse is more likely to make more than 50K. Variable is more than likely associated
  - the chisq test confirms this with a p-value less than 2.2e-16 so null hypothesis can be rejected
```{R}
  marital_status_target_table <- table(adult_data$`marital-status`, adult_data$target)
  mosaicplot(marital_status_target_table, shade = TRUE)
  chisq.test(marital_status_target_table)
```

- occupation: mosaic plot and chisq test - is associated
  - the mosaic plot shows a lot of blue and red which means that there are a lot of variables that show more or less frequent than the expected cell frequency which eludes to the variable being associated
  - the chisq test shows that the p-value is less than 2.2e-16 although there is a warning. Setting simulate.p.value to true still produces a p-value less than .05 so we can reject the null hypothesis
```{R}
  occupation_target_table <- table(adult_data$occupation, adult_data$target)
  mosaicplot(occupation_target_table, shade = TRUE)
  chisq.test(occupation_target_table)
  chisq.test(occupation_target_table, simulate.p.value = TRUE)
```

- relationship: mosaic plot and chisq test - is associated
  - the mosaic plot shows a strong likelihood that husbands and wives are more likely to make more than 50K while all other values are less likely to make more than 50K and more likely to make less than 50K. Variables is most likely associated.
  - the chisq test confirms this and produces a p-value less than 2.2e-16 which means we can reject the null hypothesis
```{R}
  relationship_target_table <- table(adult_data$relationship, adult_data$target)
  mosaicplot(relationship_target_table, shade = TRUE)
  chisq.test(relationship_target_table)
```

- race: mosaic plot and chisq test - is associated
  - the mosaic plot shows a strong association between this and the target variable. If race value is White then those people are more likely to make over 50K and less likely to make less than 50K. At the same time all other values besides Asian-PAC-Islander are less likely to make over 50K and more likely to make less than 50K.Variables are more than likely associated.
  - the chisq test produces a p-value that is less than 2.2e-16 so we can reject the null hypothesis
```{R}
  race_target_table <- table(adult_data$race, adult_data$target)
  mosaicplot(race_target_table, shade = TRUE)
  chisq.test(race_target_table)
```

- sex: mosaic plot and chisq test - is associated
  - the mosaic plot shows very strong likelihood that the variables are associated as males are more likely to make more than 50K and less likely to make less than 50K while females are more likely to make less than 50K and less likely to make more than 50K.
  - the chisq test confirms this and produces a p-value that is less than .05 so the null hypothesis can be rejected
```{R}
  sex_target_table <- table(adult_data$sex, adult_data$target)
  mosaicplot(sex_target_table, shade = TRUE)
  chisq.test(sex_target_table)
```

- capital-gain: side by side box plots and t-test - is associated
  - the side by side box plots is difficult to decipher
  - the t-test produces a p-value of less than .05 so we can reject the null hypothesis
```{R}
  plot(adult_data$`capital-gain`~as.factor(adult_data$target))
  t.test(adult_data$`capital-gain`~adult_data$target)
```

- capital-loss: side by side box plots and t-test - is associated
  - the side by side box plots is also difficult to decipher
  - the t-test produces a p-value of less than .05 so we can reject the null hypothesis
```{R}
  plot(adult_data$`capital-loss`~as.factor(adult_data$target))
  t.test(adult_data$`capital-loss`~adult_data$target)
```

- hours-per-week: side by side box plots and t-test - is associated
  - the side by side box plots show little overlap and so it is likely that the variables are associated
  - the t-test confirms this and produces a p-value of less than .05 so the null hypothesis can be rejected
```{R}
  plot(adult_data$`hours-per-week`~as.factor(adult_data$target))
  t.test(adult_data$`hours-per-week`~adult_data$target)
```

- native-country: mosaic plot and chisq test - is associated
  - the mosaic plot shows that there are a lot more observations of North_America(after combining values for data sparsity) than any other value. There are also two values (Europe and Asia) that are more likely to make more than 50K and one value (South_America) that is more likely to make less than 50K and less likely to make more than 50K
  - the chisq test produces a p-value that is less than .05 and so the null hypothesis can be rejected
```{R}
  native_country_target_table <- table(adult_data$`native-country`, adult_data$target)
  mosaicplot(native_country_target_table, shade = TRUE)
  chisq.test(native_country_target_table)
```

Summary: most variables are associated which makes me a little nervous but most of them were pretty conclusive. The following variables are the ones that are not associated and will be removed from testing and train data: fnlwgt

```{R}
  adult_train <- subset(adult_train, select = -c(fnlwgt)) 
  adult_test <- subset(adult_test, select = -c(fnlwgt)) 
```

7. Train a logistic regression model on the train data (preprocessed and transformed using above
steps) using the glm package and use it to predict “income” for the test data

```{R}
  logistic_model <- glm(as.factor(target)~age+workclass+education+`marital-status`+occupation+relationship+race+sex+`capital-gain`+`capital-loss`+`hours-per-week`+`native-country`, family = "binomial", data = adult_train)
  predictions <- predict(logistic_model, adult_test, type = "response")
  predicted.label <- factor(ifelse(predictions > 0.5, ">50K", "<=50K"))
  actual.label = adult_test$target
  t <- table(predicted.label, actual.label)
  t
  error <- (t[1,2]+t[2,1]) / sum(t)
  error
```

8. Get the cross table between the predicted labels and true labels in the test data and compute the
total error as well as the precision and recall for both income<=50K and income>50K classes.

```{R}
  t <- table(predicted.label, actual.label)
  t
  error <- (t[1,2]+t[2,1]) / sum(t)
  error
  # precision: true positives(>50K) divided by all predicted positives
  precision <- t[2,2] / (t[2,2] + t[1,2])
  precision
  # recall: true positives divided by all actual positives
  recall <- t[2,2] / (t[2,2] + t[2,1])
  recall
```

9. Balancing target variable.
```{R}
  original_levels <- lapply(adult_train, levels)
  set.seed(1234) 
  majority_class <- adult_train[adult_train$target == "<=50K",]
  minority_class <- adult_train[adult_train$target == ">50K",]
  downsampled_majority <- majority_class[sample(1:nrow(majority_class), nrow(minority_class)),]
  adult_downsampled <- rbind(downsampled_majority, minority_class)
  for (col in names(adult_downsampled)) {
    if (is.factor(adult_downsampled[[col]])) {
      levels(adult_downsampled[[col]]) <- original_levels[[col]] 
    }
  }
  table(adult_downsampled$target)
  
  # train on downsampled data
  # getting issues where downsampled data is missing factor values present in the training data, ie workclass
  # training data has 'Never-worked' values while downsampled data does not.
  logistic_downsampled <- glm(as.factor(target)~age+workclass+education+`marital-status`+occupation+relationship+race+sex+`capital-gain`+`capital-loss`+`hours-per-week`+`native-country`, family = "binomial", data = adult_downsampled)
  predictions_downsampled <- predict(logistic_downsampled, adult_test, type = "response")
  predicted_downsampled.label <- factor(ifelse(predictions_downsampled > 0.5, ">50K", "<=50K"))
  actual.label = adult_test$target
  tds <- table(predicted_downsampled.label, actual.label)
  tds
  error_ds <- (tds[1,2]+tds[2,1]) / sum(tds)
  error_ds
```

10. Repeat the steps above(7-9) but use C5.0(trials = 30).
  - Error rates:
    - C5: 12.99%
    - LogRegr: 14.76%
  - Precision:
    - C5: 78.29%
    - LogRegr: 58.93%
  - Recall:
    - C5: 63.71%
    - LogRegr: 74.46%
```{R}
  income_c5 <- C5.0(adult_train[-14], as.factor(adult_train$target), trials = 30)
  income_pred <- predict(income_c5, adult_test)
  income_confusion_matrix <- CrossTable(adult_test$target, income_pred, prop.chisq = FALSE, prop.c = FALSE, prop.r = FALSE, dnn = c('actual income', 'predicted income'))
  c5_t <- income_confusion_matrix$t
  c5_error <- (c5_t[1,2] + c5_t[2,1]) / sum(c5_t)
  c5_precision <- c5_t[2,2] / (c5_t[2,2] + c5_t[1,2])
  c5_recall <- c5_t[2,2] / (c5_t[2,2] + c5_t[2,1])
  c5_error
  c5_precision
  c5_recall
```